#ifndef UPDATE_IMAGE_LABEL_HPP
#define UPDATE_IMAGE_LABEL_HPP

#include <pugixml/src/pugixml.hpp>

#include <iostream>

/**
 * update the xml files generated by imglab of dlib
 */
class update_image_label
{
public:
    /**
      * construct the dom tree of the xml file
      * @param input_file the xml file want to update
      */
    update_image_label(std::string const &input_file,
                       std::string const &output_file);

    /**
     * update the box value based on the ratio, this function
     * is quite convenient if you want to change the image size
     * @param ratio the ratio apply on the label(ex : left = left * ratio)
     */
    void update_box_ratio_of_label(double ratio);

private:
    void set_box_value(double ratio, pugi::xml_attribute &attr) const;

    pugi::xml_document doc_;
    std::string output_file_;
};

#endif
